overlay-aurora: fix disk_layout
The CL:4164937 introduced regression preventing aurora image to build
which resulted with:

 chromite.lib.disk_layout.ConflictingPartitionOrderError: Layouts share
 partitions [1, 3, 5] but they are in different order:
 layout_to_override: [11, 6, 7, 9, 10, 2, 4, 8, 12, 5, 3, 1], layout:
 [3, 5, 1]

error.

Place partition in order: 5, 3, 1 instead of 3, 5, 1 to fix above issue.

BUG=None
TEST=Build aurora image

Change-Id: I65d0d8b2a71ba3316aa0592400f08da8ae60076a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/4254345
Auto-Submit: Grzegorz Jaszczyk <jaszczyk@google.com>
Commit-Queue: Dominik Behr <dbehr@chromium.org>
Tested-by: Grzegorz Jaszczyk <jaszczyk@google.com>
Tested-by: Dominik Behr <dbehr@chromium.org>
Reviewed-by: Dominik Behr <dbehr@chromium.org>