Remove sama5d3 overlay
The sama5d3 overlay uses chromeos-3.14 which is about to go
EOL/obsolete. Attempts to switch to a more recent kernel failed
because the existing overlay does not build. More specifically,
u-boot fails to compile; compile errors suggest that the system
tries to build with i386 compile options. Example error:

armv7a-cros-linux-gnueabihf-gcc.real: error:
			unrecognized argument in option '-march=i386'

On top of that, the chromeos-3.14 kernel fails to compile as well.

fs/ext4/inode.c: In function 'ext4_setattr':
fs/ext4/inode.c:4878:2: error:
			#error POSIX_ACL not supported in 3.18 backport

Apparently the overlay is not in use and no one even noticed
that it fails to build. Remove it.

BUG=chromium:1088203, chromium:942866
TEST=CQ

Change-Id: I4ac1c7ff555218df056fc7e3f49f32f7847f8ca3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/2224767
Reviewed-by: Kirtika Ruchandani <kirtika@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>