chipset-skl: restore toolchain.conf
We restored chipset-skl in https://crrev.com/c/5345144 and removed
toolchain.conf since we aren't building firmware.  However, we still
need to define a default toolchain else `setup_board --board=caroline`
fails with:

  chromite.lib.sysroot_lib.ConfigurationError: No default toolchain
  could be found.

BUG=b:321067912
TEST=build and deploy caroline

Change-Id: Ifc80af41aa2383f04d6b22d653d8a7db162cbe6b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/5359489
Auto-Submit: Ross Zwisler <zwisler@google.com>
Commit-Queue: Jack Rosenthal <jrosenth@chromium.org>
Tested-by: Ross Zwisler <zwisler@google.com>
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>
Commit-Queue: Ross Zwisler <zwisler@google.com>